const selladoProvincia = [
    {"provincia":"buenos aires","sellado":150},
    {"provincia":"cordoba","sellado":200},
    {"provincia":"santa fe","sellado":350},
    {"provincia":"ciudad de buenos aires","sellado":280},
    {"provincia":"mendoza","sellado":150},
    {"provincia":"tucuman","sellado":250},
    {"provincia":"entre rios","sellado":180},
    {"provincia":"salta","sellado":220},
    {"provincia":"misiones","sellado":150},
    {"provincia":"chaco","sellado":210},
    {"provincia":"corrientes","sellado":180},
    {"provincia":"santiago del estero","sellado":250},
    {"provincia":"san juan","sellado":140},
    {"provincia":"jujuy","sellado":190},
    {"provincia":"rio negro","sellado":150},
    {"provincia":"neuquen","sellado":220},
    {"provincia":"formosa","sellado":120},
    {"provincia":"chubut","sellado":160},
    {"provincia":"san luis","sellado":200},
    {"provincia":"catamarca","sellado":180},
    {"provincia":"la rioja","sellado":250},
    {"provincia":"la pampa","sellado":150},
    {"provincia":"santa cruz","sellado":220},
    {"provincia":"tierra del fuego","sellado":180},
]

